name: ci
description: Installs dependencies

runs:
  using: composite
  steps:
    # General Tests
    - name: Install packages
      shell: bash
      run: flutter pub get

    # - name: Generate code
    #   shell: bash
    #   run: flutter pub run build_runner build --delete-conflicting-outputs

    - name: Verify formatting and analyze project source
      shell: bash
      run: dart format --output=none --set-exit-if-changed .

    - name: Analyze project source
      shell: bash
      run: flutter analyze
    